# https://stackoverflow.com/questions/75955457/substrate-node-template-cannot-create-a-runtime-error-othercannot-deserialize
[toolchain]
channel = "1.84.1"
components = [
    "cargo",
    "clippy",
    "rust-src",
    "rustfmt",
]
targets = ["wasm32-unknown-unknown"]
profile = "default" # include rustfmt, clippy
